name: Build VCV Rack Plugin
on: [workflow_dispatch]

env:
  rack-sdk-version: 2.beta.1

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: Linux,
            os: ubuntu-latest,
            prepare-os: sudo apt update && sudo apt install -y libglu-dev,
            os-slug: lin
          }
        - {
            name: MacOS,
            os: macos-latest,
            prepare-os: "",
            os-slug: mac
          }
        - {
            name: Windows,
            os: windows-latest,
            prepare-os: export CC=gcc,
            os-slug: win
          }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get Rack-SDK
        run: |
          pushd $HOME
          curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-${{ matrix.config.os-slug }}.zip
          unzip Rack-SDK.zip
      - name: Build plugin
        run: |
          ${{ matrix.config.prepare-os }}
          export RACK_DIR=$HOME/Rack-SDK
          make -j dep
          make -j dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ${{ matrix.config.name }}